### ISSUE TITLE
Admin panel

### ISSUE THREAD

**Issue by AnetaRolnik** [AnetaRolnik/AI_3D#1]
- [x] add the phone number field in the Clients section
- [x] add the email field in the Messages section
- [x] add a field with the date of ending the registration for the training in the Trainings section
- [ ] fix the price field in the Trainings section (the prices from Courses should automatically appear)
- [x] fix the registration for training

**Comment by jrkapciak** [comment]
4. Can't be implement at the moment.
5. Can't recreate error with sign ups.
